### ISSUE TITLE
init exception

### ISSUE THREAD

**Issue by AndroidCrazyBoy** [Web3Auth/web3auth-android-sdk#40]
AndroidRuntime: FATAL EXCEPTION: main
java.lang.ExceptionInInitializerError
        at com.web3auth.core.Web3Auth.initiateKeyStoreManager(Web3Auth.kt:83)
        at com.web3auth.core.Web3Auth.<init>(Web3Auth.kt:59)

**Comment by AndroidCrazyBoy** [comment]
if app has own application. Web3AuthApp can not been initalizer。

**Comment by grvgoel81** [comment]
This has been resolved. Please use latest sdk version 3.2.0
