### ISSUE TITLE
debug reinstall crash 

### ISSUE THREAD

**Issue by peterQin18** [Web3Auth/web3auth-android-sdk#60]
kotlin.UninitializedPropertyAccessException: lateinit property sharedPreferences has not been initialized
 at com.web3auth.session_manager_android.keystore.KeyStoreManager.savePreferenceData(KeyStoreManager.kt:127)
at com.web3auth.session_manager_android.SessionManager.saveSessionId(SessionManager.kt:54)
at com.web3auth.core.Web3Auth.setResultUrl(Web3Auth.kt:120)

**Comment by grvgoel81** [comment]
Pls use latest sdk version,
